language: swift
osx_image: xcode9.3

script:
  - carthage update HTMLSpecialCharacters MiniKeychain --platform ios
  - xcodebuild test -project reddift.xcodeproj -scheme reddift-iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"